image: python:3.11
pages:
    stage: deploy
    script:
        - pip install -r requirements.txt
        - mkdocs build
        - mv site public
    artifacts:
        paths:
            - public
    only:
        - master
