#!/bin/sh
# vim: syntax=sh

# $0 refer to the name of the script
script_directory=$(dirname "$0")

# Specify the filename you want to check
file_to_check="highscores.csv"

# Construct the full path to the file
full_path="$script_directory/$file_to_check"

if [ -e "$full_path" ]; then
    echo "File '$file_to_check' exists in the script's directory."
else
    echo "File '$file_to_check' does not exist in the script's directory."
    touch "highscores.csv"
fi

counter=0
score=0
broken=0
echo "Enter a name"
read name


while [ "$counter" -lt 10 ]; do
    counter=$((counter+1))
    random_number=$(( (RANDOM % 6) + 1 ))
    echo "Enter a number between 1-6 (enter 0 to exit): "
    read input

    if [ "$input" -eq 0 ]; then
        echo "Exiting the loop."
        broken=1
        break
    elif [ "$input" -gt 6 ]; then
        echo "Number must be between 1-6, try again"
        counter=$((counter-1))

    elif [ "$input" -eq $random_number ]; then
        echo "Correct."
        score=$((score+1))
    else
        echo "Incorrect"
    fi
done

if [ "$broken" -eq 0 ]; then
    echo $name,$score >> "$full_path"
    echo "final score: "$score""
    # -t , tells comma is seperator, -k2 sorts on second value, -nr = numerical reverse sort
    sorted_csv=$(sort -t',' -k2 -nr "$full_path")
    echo "High score:"

cat << "END"
  _    _ _       _        _____
 | |  | (_)     | |      / ____|
 | |__| |_  __ _| |__   | (___   ___ ___  _ __ ___
 |  __  | |/ _` | '_ \   \___ \ / __/ _ \| '__/ _ \
 | |  | | | (_| | | | |  ____) | (_| (_) | | |  __/
 |_|  |_|_|\__, |_| |_| |_____/ \___\___/|_|  \___|
            __/ |
           |___/
END

    echo "$sorted_csv" | head -n 10



else
    echo "exited game"
fi
